# Generated by Django 4.2.1 on 2023-05-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partnerprefarence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age_1', models.CharField(max_length=62322222222222222)),
                ('Age_2', models.CharField(max_length=62322222222222222)),
                ('Height_1', models.CharField(max_length=62322222222222222)),
                ('Height_2', models.CharField(max_length=62322222222222222)),
                ('Relligion', models.CharField(max_length=62322222222222222)),
                ('State', models.CharField(max_length=62322222222222222)),
                ('Caste', models.CharField(max_length=62322222222222222)),
                ('Complexion', models.CharField(max_length=62322222222222222)),
                ('Residency_Status', models.CharField(max_length=62322222222222222)),
                ('Country', models.CharField(max_length=62322222222222222)),
                ('Education', models.CharField(max_length=62322222222222222)),
                ('Occupation', models.CharField(max_length=62322222222222222)),
                ('Partner_Expectations', models.CharField(max_length=62322222222222222)),
                ('Looking_for', models.CharField(max_length=62322222222222222)),
            ],
        ),
    ]
