# Generated by Django 4.2.1 on 2023-05-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('religion', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('caste', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('height', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('occupation', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('income', models.IntegerField(blank=True, default=None, null=True)),
                ('D_O_B', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Mother_Tonge', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Education', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Location', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Hobbies', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Intersts', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Siblings', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('profile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileapi.profile')),
            ],
        ),
    ]
