# Generated by Django 4.2.1 on 2023-05-08 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SilverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_profiles', models.IntegerField(default=1)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membershipapi.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity_period', models.IntegerField(default=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membershipapi.plan')),
            ],
        ),
        migrations.CreateModel(
            name='GoldPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_profiles', models.IntegerField(default=40)),
                ('validity_period', models.IntegerField(default=3)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membershipapi.plan')),
            ],
        ),
        migrations.CreateModel(
            name='DedicatedRMPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Membershipapi.plan')),
            ],
        ),
    ]
