# Generated by Django 4.2.1 on 2023-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Number', models.IntegerField()),
                ('Alternative_Mobile_Number', models.CharField(max_length=62322222222222222)),
                ('Convinient_Time_To_Call', models.CharField(max_length=62322222222222222)),
                ('Email', models.EmailField(max_length=444444)),
                ('Show_Permanent_Address', models.CharField(max_length=62322222222222222)),
                ('Show_Working_Address', models.CharField(max_length=62322222222222222)),
            ],
        ),
    ]
