# Generated by Django 4.2.1 on 2023-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=80)),
                ('PhoneNumber', models.IntegerField()),
                ('Message', models.CharField(max_length=150)),
                ('Subject', models.CharField(max_length=277777777)),
            ],
        ),
    ]
