# Generated by Django 4.2.1 on 2023-05-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default=None, max_length=222222222, null=True)),
                ('Title', models.ImageField(blank=True, default=None, null=True, upload_to='success_stories')),
                ('date', models.DateField()),
            ],
        ),
    ]
