# Generated by Django 4.2.1 on 2023-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=150)),
                ('Occupation', models.CharField(max_length=150)),
                ('Occupation_Details', models.CharField(max_length=150)),
                ('Annual_Income', models.CharField(max_length=150)),
                ('Employed_in', models.CharField(max_length=150)),
                ('Special_Cases', models.CharField(max_length=150)),
                ('Education_Details', models.CharField(default='null', max_length=150)),
                ('Income_type', models.CharField(default='null', max_length=150)),
                ('Working_Hours', models.CharField(default='null', max_length=150)),
                ('Working_Location', models.CharField(max_length=150)),
                ('Height', models.CharField(default='null', max_length=150)),
                ('Weight', models.CharField(default='null', max_length=150)),
                ('Blood_Group', models.CharField(default='null', max_length=150)),
                ('Complexion', models.CharField(default='null', max_length=150)),
            ],
        ),
    ]
